Map cross
tvgb/sau-client pull request #34
Opened 2021-02-11 13:57 UTC by Kimia97

2021-02-11 14:49 UTC, tvgb commented on src/app/pages/map/map.page.ts
> +	 	this.gpsService.startTrackingInterval();
Trur nesten du må fiks indenteringa på den linja her altså 👎

2021-02-11 14:49 UTC, tvgb requested changes
Nesten godt jobba!

2021-02-11 14:53 UTC, Kimia97 commented on src/app/pages/map/map.page.ts
> +	 	this.gpsService.startTrackingInterval();
jeg lover jeg har prøvd men hver gang jeg lagrer så fucker den opp igjen

2021-02-12 11:45 UTC, tvgb approved these changes

2021-02-12 11:45 UTC, merged