Update summary
tvgb/sau-client pull request #39
Opened 2021-02-12 14:49 UTC by Kimia97

-Lagt til sider for register injured og dead, informasjonen hentes inn i fieldtrip summary

2021-02-12 15:23 UTC, tvgb commented on src/app/pages/registration/register-dead/register-dead-routing.module.ts
> +  imports: [RouterModule.forChild(routes)],
Litt indentering her ja

2021-02-12 15:23 UTC, tvgb commented on src/app/pages/registration/register-injured/register-injured-routing.module.ts
> +  imports: [RouterModule.forChild(routes)],
Whooopsie

2021-02-12 15:25 UTC, tvgb requested changes
Hehehe

2021-02-15 12:04 UTC, Kimia97 commented
fikset nå!

2021-02-15 12:27 UTC, tvgb approved these changes

2021-02-15 12:27 UTC, merged