Authentication
tvgb/sau-client pull request #43
Opened 2021-02-18 14:25 UTC by tvgb

2021-02-19 09:54 UTC, Kimia97 requested changes
good job boi

2021-02-19 09:54 UTC, Kimia97 commented on src/app/pages/settings/settings.page.ts
> +				// Gi beskjed om at det ikke fungerte!
er det noe som kommer senere eller har du glemt?

2021-02-22 15:14 UTC, tvgb commented on src/app/pages/settings/settings.page.ts
> +				// Gi beskjed om at det ikke fungerte!
Nei det e noe som potensielt kommer senere.

2021-02-22 15:15 UTC, Kimia97 approved these changes

2021-02-22 15:15 UTC, merged